### ISSUE TITLE
Error: Missing command

### ISSUE THREAD

**Issue by trevortomesh** [Nekmo/gkeep#1]
I am trying to set up gkeep for the first time and I have created an auth.txt, but I get the following error issue:

INPUT:
`gkeep --auth /home/trevor/gkeep/auth.txt`

OUTPUT:
```
Usage: gkeep [OPTIONS] COMMAND [ARGS]...

Error: Missing command.
```

**Comment by Nekmo** [comment]
You need define a command to use. Available commands are available on README doc and using --help:

https://github.com/Nekmo/gkeep/blob/master/README.rst#items

Currently only items commands are available. You can use `--auth <file>` before any item command.

Regards

**Comment by Nekmo** [comment]
Closed due to inactivity.
