### ISSUE TITLE
LoginError

### ISSUE THREAD

**Issue by JulianSauer** [Nekmo/gkeep#15]
I tried adding an item with ` gkeep --auth auth.txt add-item <note id> "TEST"` where auth.txt contains my email and password. However those seem to be invalid:

    [Error] GKeep Exception:
    LoginError: Check credentials file. The syntax is: <username> <password>.

I am quite sure that my email and password are correct - any idea why it is not working?

**Comment by Nekmo** [comment]
Surely the file auth.txt contains errors. Try using your username instead of email and delete spaces and extra line breaks.

**Comment by JulianSauer** [comment]
How do I find my username? There only seems to be a display name.

I simply ran `echo 'my.email@mail.com password > auth.txt`

**Comment by MortimerMcMire315** [comment]
This could be related to [](https://github.com/kiwiz/gkeepapi/issues/20).

**Comment by LNQ** [comment]
I keep getting the same error. My credentials are OK, I dont use 2factorauth.

what about non [a-z][A-Z] characters in the password. Could that be a problem? What if I have a literal space character in my password?

**Comment by Nekmo** [comment]
> I keep getting the same error. My credentials are OK, I dont use 2factorauth.

This normally should not be a problem.

**Comment by LNQ** [comment]
then this is not normal ;-)

I dont have a literal space character in my password. But there are several special characters. Dont know is that could be an issue.
I want this to work! Can I help? Could provide further info.

My setup is the termux-app running on my phone. I want to be able to control my shopping list etc through tasker. I know, this sounds wierd but thats how I roll! So Im on python 3.7.2

Ive got syncthing running in termux as well and it runs like hell.

**Comment by jakubLangr** [comment]
I have the same issue @Nekmo and I followed pretty much the same procedure as @syslino 

I am also somewhat surprised that it is so easy to auth with Google Keep

**Comment by notflip** [comment]
Same issue! Authentication issue while providing the correct email and password

**Comment by Nekmo** [comment]
The next version will include improvements for the login. I will need beta-testers for testing!

**Comment by notflip** [comment]
Let me know when you do, I would be happy to help!

**Comment by Nekmo** [comment]
@notflip do you have "Less secure apps" activated in your Google account?

https://support.google.com/accounts/answer/6010255

Try the unsafe mode (activated mode): https://myaccount.google.com/

**Comment by Nekmo** [comment]
If the error continues, install the latest version from the development branch:

```
pip install https://github.com/Nekmo/gkeep/archive/develop.zip
```

Incidence #25 improves the login process.

**Comment by notflip** [comment]
Question is, how safe is it to allow less-safe-apps, how are my credentials stored?

**Comment by Nekmo** [comment]
_allow less-safe-apps_ mode is less secure with unreliable apps but you can turn it back on later. You can check the source code before installing.

In the development branch your credentials are stored in `~/.config/gkeep`. You can delete the folder after testing.

**Comment by Nekmo** [comment]
Closed due to inactivity.
