### ISSUE TITLE
Delete Checked Items Action

### ISSUE THREAD

**Issue by taviso** [Nekmo/gkeep#39]
Hello, is there a way to replicate the "Delete Checked Items" action using gkeep?

![Screenshot 2021-01-19 084545](https://user-images.githubusercontent.com/123814/105065475-c1ba2a80-5a32-11eb-8c96-addbbb1b3c04.png)

I use gkeep all the time, I have a little receipt printer on my desk, and run `gkeep notes get ... | lpr` to print todo lists, grocery lists, addresses, etc. 😃

**Comment by Nekmo** [comment]
Hi, it is currently not possible without using multiple bash commands, but can be added as a proposal :)

**Comment by Nekmo** [comment]
Closed due to inactivity.
