### ISSUE TITLE
Cannot login with password or app password

### ISSUE THREAD

**Issue by Laanan** [Nekmo/gkeep#40]
Hello, so I can't login via my regular gmail password or an app password. Installing with pip3 does not create an auth file (or any file, for that matter) in ~/.config. What is the format of the auth.json file and can I just manually enter my email address and app password into that file?

**Comment by Nekmo** [comment]
Hello, the syntax is:

```
$ cat ~/.config/gkeep/auth.json
{"username": "yourname", "password": "yourpassword"}
```

**Comment by Nekmo** [comment]
Closed due to inactivity.
